name: Coverage

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - "*"

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: node:16-buster
      env:
        CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: |
          apt-get update
          apt-get install -y cmake libflac-dev flac lcov
      - name: Install
        run: npm ci
      - name: Build & Test
        run: ./scripts/coverage.sh rebuild
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/combined.info
