name: Node CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node:
          - version: 10
            napi: 6
          - version: 12
            napi: 6
          - version: 12
            napi: 7
          - version: 14
            napi: 7
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node.version }}-buster
      env:
        CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: |
          apt-get update
          apt-get install -y cmake libflac-dev flac
      - name: Install
        run: npm install
      - name: Build
        run: |
          npx cmake-js configure --CDFLAC_BINDINGS_USE_EXTERNAL_LIBRARY=ON --CDnapi_build_version=${{ matrix.node.napi }}
          npx cmake-js build
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
