name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm install
      env:
        CI: true

  test-10:
    runs-on: ubuntu-latest
    container:
      image: node:10-buster
      env:
        CI: true
      volumes:
        - $GITHUB_WORKSPACE:/app

    steps:
    - name: Test
      run: |
        apt-get update
        apt-get install -y cmake libflac-dev
        cd app
        npm test

  test-10:
    runs-on: ubuntu-latest
    container:
      image: node:12-buster
      env:
        CI: true
      volumes:
        - $GITHUB_WORKSPACE:/app

    steps:
    - name: Test
      run: |
        apt-get update
        apt-get install -y cmake libflac-dev
        cd app
        npm test
