name: Node CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node: [10, 12, 13]
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-buster
      env:
        CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        apt-get update
        apt-get install -y cmake libflac-dev flac
    - name: Install
      run: npm install
    - name: Workarounds
      run: |
        patch node_modules/node-addon-api/napi-inl.h < .github/workflows/avoid-double-delete-ref-in-object-wrap.patch
    - name: Build
      run: npm run cmake-js -- build
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
